# Generated by Django 5.2.5 on 2025-08-14 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Phone must be in the format +1234567890 or 123-456-7890', regex='^(\\+\\d{1,15}|\\d{3}-\\d{3}-\\d{4})$')]),
        ),
    ]
